

BATCH_DIM = (None, 16, 100)
HIDDEN_DIM = 256
OUTPUT_DIM = 88
OUTPUT_LEN = 16
ENCODE_DEPTH = 3
DECODE_DEPTH = 3
TEACHER_FORCE = False
FILE_NAME = 'run.log'
TRAIN_LOG = 'seq2seq_train.log'
NUM_EPOCHS = 50